language: java
jdk:
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk-ea
install:
  - mvn test -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#script:
#  - mvn test -B -X
matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk12
    - jdk: openjdk13
    - jdk: openjdk14
    - jdk: openjdk-ea